## 1. Construct a 5x3 matrix for the value of x
## Object x<-1:15

In [5]:
x <- (1:15)
x_matrix <- matrix(x,5)
x_matrix

     [,1] [,2] [,3]
[1,] 1     6   11
[2,] 2     7   12
[3,] 3     8   13
[4,] 4     9   14
[5,] 5    10   15

## 2. Write a program to generate the following 4x4 matrix

In [11]:
zero_matrix <- matrix(0, 4, 4)
zero_matrix

     [,1] [,2] [,3] [,4]
[1,] 0    0    0    0
[2,] 0    0    0    0
[3,] 0    0    0    0
[4,] 0    0    0    0

## 3. Write a prgram to generate the following 3x8 matrix The object x<-1:8

### 1. cbind()

In [ ]:
c1 <- c(1, 8, 3)
c2 <- c(2, 7, 3)
c3 <- c(3, 6, 3)
c4 <- c(4, 5, 3)
c5 <- c(5, 4, 3)
c6 <- c(6, 3, 3)
c7 <- c(7, 2, 3)
c8 <- c(8, 1, 3)
cbind_matrix <- matrix(cbind(c1, c2, c3, c4, c5, c6, c7, c8), 3)
cbind_matrix

### 2. rbind()

In [ ]:
r1 <- c(1, 2, 3, 4, 5, 6, 7, 8)
r2 <- c(8, 7, 6, 5, 4, 3, 2, 1)
r3 <- c(3, 3, 3, 3, 3, 3, 3, 3)
rbind_matrix <- matrix(rbind(r1, r2, r3), 3)
rbind_matrix

### 3. rev()

In [ ]:
rbind_for_rev <- rbind(r3, r1, r2)
rev_matrix <- matrix(rev(rbind_for_rev), 3)
rev_matrix

### 4. rep()

In [ ]:
r3_rep = rep(3, 8)
rep_matrix = matrix(rbind(r1, r2, r3_rep), 3)
rep_matrix

## 4. Chose two different(x,y) 4x4 matrix to perform the following arithmetic operations

In [12]:
x <- matrix((1:16), 4)
y <- matrix((16:1), 4)
x
y

     [,1] [,2] [,3] [,4]
[1,] 1    5     9   13
[2,] 2    6    10   14
[3,] 3    7    11   15
[4,] 4    8    12   16

     [,1] [,2] [,3] [,4]
[1,] 16   12   8    4
[2,] 15   11   7    3
[3,] 14   10   6    2
[4,] 13    9   5    1

### a. (x + y)

In [13]:
x_plus_y <- x + y
x_plus_y

     [,1] [,2] [,3] [,4]
[1,] 17   17   17   17
[2,] 17   17   17   17
[3,] 17   17   17   17
[4,] 17   17   17   17

### b. (x-y)

In [14]:
x_minus_y <- x - y
x_minus_y

     [,1] [,2] [,3] [,4]
[1,] -15  -7   1     9
[2,] -13  -5   3    11
[3,] -11  -3   5    13
[4,]  -9  -1   7    15

### c. (x*y)

In [15]:
x_multi_y <- x*y
x_multi_y

     [,1] [,2] [,3] [,4]
[1,] 16   60   72   52
[2,] 30   66   70   42
[3,] 42   70   66   30
[4,] 52   72   60   16

### d. (x%*%y)

In [16]:
x_muldulo2_y <- x%*%y
x_muldulo2_y

     [,1] [,2] [,3] [,4]
[1,] 386  274  162  50
[2,] 444  316  188  60
[3,] 502  358  214  70
[4,] 560  400  240  80

### e. Difference between (c) &(d)

In [17]:
diff <- x_multi_y - x_muldulo2_y
diff

     [,1] [,2] [,3] [,4]
[1,] -370 -214  -90   2
[2,] -414 -250 -118 -18
[3,] -460 -288 -148 -40
[4,] -508 -328 -180 -64

### f. Inverse of y

In [18]:
library(pracma)

diff_inv <- inv(diff)
diff_inv

Warning message in inv(diff):
“Matrix appears to be singular.”

     [,1] [,2] [,3] [,4]
[1,] Inf  Inf  Inf  Inf
[2,] Inf  Inf  Inf  Inf
[3,] Inf  Inf  Inf  Inf
[4,] Inf  Inf  Inf  Inf

In [19]:
a1 <- c(3, 2, 8)  
a2 <- c(6, 3, 2)  
a3 <- c(5, 2, 4)
a <- rbind(a1, a2, a3)
a_inv <- inv(a)
a_inv

     a1         a2         a3
[1,] -0.2857143 -0.2857143  0.7142857
[2,]  0.5000000  1.0000000 -1.5000000
[3,]  0.1071429 -0.1428571  0.1071429

### g. (z <- x / y)

In [ ]:
z <- x/y
z

### h. Transpose of z

In [ ]:
z_transpose = t(z)
z_transpose

### . Diagonal of transpose matrix

In [ ]:
z_diagonal <- diag(z)
z_diagonal

In [20]:
# Diagonal matrix
dia_matrix <- diag(3, 3, 3)
dia_matrix

     [,1] [,2] [,3]
[1,] 3    0    0
[2,] 0    3    0
[3,] 0    0    3

## 5. Difference between (i) & (ii)

In [21]:
# x_i -> give the element rowise
x_i <- matrix(1:9, 3, 3, byrow=TRUE)
x_i

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6
[3,] 7    8    9

In [22]:
# x_ii -> give the element columnwise
x_ii <- matrix(1:9, 3, 3)
x_ii

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

## 6.Which function can we use for inner product and outer product in matrix calculation?

### 1. Inner product

In [26]:
library(geometry)
inner_product <- dot((1:3), (1:3))
inner_product

[1] 14

### 2. Outter product

In [24]:
outter_product <- outer((1:3), (1:3), '-')
outter_product

     [,1] [,2] [,3]
[1,] 0    -1   -2
[2,] 1     0   -1
[3,] 2     1    0

## 7. Explain the use of all.equal() function in Matrix with a sample program.

In [27]:
isTrue <- all.equal((1:3), (1:3))
isTrue

[1] TRUE

In [28]:
isFalse <- all.equal(pi, 3.14)
isFalse

[1] "Mean relative difference: 0.0005069574"

## 8.Explain the use of dim() function with a sample program.

In [29]:
dim <- 1:12; dim(dim) <- c(3, 4)
dim

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

## 9. Use of $ operator, and square brackets [] in List with example program.

In [32]:
list_data <- list(c("January","Febuary","March"), matrix(c(3,9,5,1,-2,8), nrow = 2), list("green",12.3))
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

In [33]:
list_data[1]

$`1st Quarter`
[1] "January" "Febuary" "March"

In [34]:
list_data$'A_Matrix'

     [,1] [,2] [,3]
[1,] 3    5    -2
[2,] 9    1     8

In [35]:
list_data$'A Inner list'[2]

[[1]]
[1] 12.3

## 10. Explain ifelse() with example.

In [36]:
name <- readline(prompt="Enter name: ")
if (name == 'SokHeng') {
    print(paste('Heh', name))
} else {
    print(paste('Bye Handsome'))
}

Enter name: SokHeng
[1] "Heh SokHeng"

## 11.Write a program to get the weight and height from the user to calculate the following cases
a. If your BMI is less than 18.5, it falls within the underweight range.
b. If your BMI is 18.5 to <25, it falls within the normal.
c. If your BMI is 25.0 to <30, it falls within the overweight range.
d. If your BMI is 30.0 or higher, it falls within the obese range.

In [41]:
calcBMI <- function(weight, height) {
  return(round(weight / (height * height), 0))
}

weight <- readline(prompt = "enter your weight (kg): ")
height <- readline(prompt = "enter your height (m): ")

weight <- as.double(weight)
height <- as.double(height)

bmi = calcBMI(weight = weight, height = height)

if (bmi < 18.5) {
    print(paste('BMI: ', bmi, ' - you are under weight'))
} else if (18.5 < bmi && bmi < 25) {
    print(paste('BMI: ', bmi, ' - you are normal'))
} else if (25 < bmi && bmi < 30) {
    print(paste('BMI: ', bmi, ' - you are over weight'))
} else if (30 < bmi) {
    print(paste('BMI: ', bmi, ' - you are obese'))
}

enter your weight (kg): 1200
enter your height (m): 170
[1] "BMI:  0  - you are under weight"

 ## 12.Difference between List and Data frame with an example program.

### 1 List

In [42]:
my_list <- list(c("January","February","March"), matrix(c(3,9,5,1,-2,8), nrow = 2), list("green",12.3))
print(paste('my list: ', my_list))

[1] "my list:  c(\"January\", \"February\", \"March\")"
[2] "my list:  c(3, 9, 5, 1, -2, 8)"
[3] "my list:  list(\"green\", 12.3)"

### 2 Dataframe

In [43]:
# A data frame is used for storing data tables. It is a list of vectors of equal length. Data frame makes it easy for data analyzing process
n <- c(1, 2, 3)
s <- c("aa", "bb", "cc")
b <- c(TRUE, FALSE, TRUE)
df <- data.frame(n, s, b)
df

  n s  b
1 1 aa  TRUE
2 2 bb FALSE
3 3 cc  TRUE

## 13. Difference between repeat and while loop with example program.

### 1 while loop

In [45]:
i<- 0
while (i!=2) {print(i);i<-i+1}

[1] 0
[1] 1

### 2 repeat

In [46]:
j <- 1
repeat {
    print(j)
    j <- j+1
    if (j == 6){
        break
    }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5